### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by vinodkahuja** [wirelessfuture/pywebcapture#6]
How to fix it when you receive time out error from selenium after processing a certain number of images in csv list.

I got the following error. 
Message: timeout: Timed out receiving message from renderer: 298.911

**Comment by wirelessfuture** [comment]
Hi @vinodkahuja Can you please provide any additional logs, was it an error? If so then please provide the stacktrace so I can take look. Also please provide: 

- python version
- chromium webdriver version
- your chrome browser version and the OS type and version please.
